### ISSUE TITLE
How can I get the predicted result?

### ISSUE THREAD

**Issue by MurphyJUAN** [RozDavid/LanguageGroundedSemseg#14]
Hi, I am using ScanNet3D200 to do the semantic segmentation.
If I want to get and export the predicted result to .txt file, how can I do that?
(Should I use the 'save_predictions()' function? but how?)
Thank you.

**Comment by RozDavid** [comment]
Hey @MurphyJUAN, 

I assume you would like to submit it to the benchmark, where instead of the voxelized coordinates, you would rather want to evaluate on the full cloud. For this you should use first the standard evaluation pipeline followed by the `test_pointcloud` method which is automatically called if you set the `test_original_pointcloud` flag to true. 

With that you associate the point to voxel predictions with a simple KNN search, that you can save with a simple numpy save command in either npy or txt format. The saving you can do with either the `save_predictions` function, or you can add an etxtra line simply to `test_pointcloud`.

Hope this helps,
David

**Comment by MurphyJUAN** [comment]
I see it.
Thank you so much for your reply.
🤩
